### PR TITLE
build against .net core 2.1

### PR DESCRIPTION
**Pull request by derhally**
This change is [Reviewable](https://reviewable.io/reviews/derhally/dbcontextscope/1)

### CODE REVIEW

**Comment by derhally** [comment]
*[a discussion](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrLYe_Bv_vWyU1bOkr:-LMrLYe_Bv_vWyU1bOks:b-9dkrow) (no related file):*
Please add some comments

---

**Comment by derhally** [comment]
*[a discussion](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrSkql4nxVM6IJmFvH:-LMrSkql4nxVM6IJmFvI:biaqmnb) (no related file):*
@joshclark @onarres  @janetr1023  notice that the PR is blocked until the review is approved in reviewable.

---

**Comment by derhally** [comment]
*[a discussion](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrLYe_Bv_vWyU1bOkr:-LMrh937CjTsWAJ82hSL:b-jjr2bh) (no related file):*
<details><summary><i>Previously, joshclark (Josh Clark) wrote…</i></summary><blockquote>

What kind of comments would you like?
</blockquote></details>

The nice kind

---

**Comment by janetr1023** [comment]
*[a discussion](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrLYe_Bv_vWyU1bOkr:-LMrhdUI26gSTe08fGIW:b-a35dkd) (no related file):*
<details><summary><i>Previously, derhally (Zeid) wrote…</i></summary><blockquote>

The nice kind
</blockquote></details>

Nice, and i'm not batching this for later Publish, but i liked the popup that told me to send them all later. How do i save it for later?

---

**Comment by janetr1023** [comment]
___
*[DemoApplication/Program.cs, line 19 at r1](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrk0ftCaf6dQDlCG39:-LMrk0ftCaf6dQDlCG3A:b14z1m6) ([raw file](https://github.com/derhally/dbcontextscope/blob/331dfb3266f9833fd60ec37efbce34f0e3812fd0/DemoApplication/Program.cs#L19)):*
> ```Smalltalk
> 			var dbContextScopeFactory = new DbContextScopeFactory();
> 			var ambientDbContextLocator = new AmbientDbContextLocator();
> 			var userRepository = new UserRepository(ambientDbContextLocator);
> ```

ok i like that i can easily add things on lines that have not changed

**Comment by derhally** [comment]
___
*[DemoApplication/Program.cs, line 19 at r1](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrk0ftCaf6dQDlCG39:-LMrlTZ93d3TJsRbQMit:b9w54zf) ([raw file](https://github.com/derhally/dbcontextscope/blob/331dfb3266f9833fd60ec37efbce34f0e3812fd0/DemoApplication/Program.cs#L19)):*
<details><summary><i>Previously, janetr1023 (Janet Roberts) wrote…</i></summary><blockquote>

ok i like that i can easily add things on lines that have not changed
</blockquote></details>

Yes.  this UI is so much better than github.   .

**Comment by janetr1023** [comment]
___
*[DemoApplication/Migrations/20180906203009_InitialCreate.cs, line 10 at r1](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrL9U46IjX3OL2UqLr:-LMrlgkWD_rwOX4RRVf9:b-7rpoby) ([raw file](https://github.com/derhally/dbcontextscope/blob/331dfb3266f9833fd60ec37efbce34f0e3812fd0/DemoApplication/Migrations/20180906203009_InitialCreate.cs#L10)):*
<details><summary><i>Previously, derhally (Zeid) wrote…</i></summary><blockquote>

@janetr1023 what do you think of this change?
</blockquote></details>

I hate EF :-) and there are no changes, this is a new file. On that topic how to i see all the files where i have put a comment. When i open the file matrix i dont see my icon, only you and josh

**Comment by derhally** [comment]
___
*[DemoApplication/Migrations/20180906203009_InitialCreate.cs, line 10 at r1](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrL9U46IjX3OL2UqLr:-LMrmMTH9ZehWWEirhJM:b-c80rh5) ([raw file](https://github.com/derhally/dbcontextscope/blob/331dfb3266f9833fd60ec37efbce34f0e3812fd0/DemoApplication/Migrations/20180906203009_InitialCreate.cs#L10)):*
<details><summary><i>Previously, janetr1023 (Janet Roberts) wrote…</i></summary><blockquote>

I hate EF :-) and there are no changes, this is a new file. On that topic how to i see all the files where i have put a comment. When i open the file matrix i dont see my icon, only you and josh
</blockquote></details>

@janetr1023 those icons are there to show you who reviewed that file.

**Comment by onarres** [comment]
___
*[Mehdime.Entity/Implementations/DbContextScope.cs, line 99 at r1](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrqlr08ESUcJVVCTHC:-LMrqlr1AzWyKfFHZPVm:b-f83c4e) ([raw file](https://github.com/derhally/dbcontextscope/blob/331dfb3266f9833fd60ec37efbce34f0e3812fd0/Mehdime.Entity/Implementations/DbContextScope.cs#L99)):*
> ```Smalltalk
>         }
> 
>         public async Task<int> SaveChangesAsync(CancellationToken cancelToken = default(CancellationToken))
> ```

I like forcing people to send the token in rather than giving them a convenient way out

**Comment by derhally** [comment]
___
*[Mehdime.Entity/Implementations/DbContextScope.cs, line 99 at r1](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrqlr08ESUcJVVCTHC:-LMrrzBtCXftKyszlY5U:b9y3dgy) ([raw file](https://github.com/derhally/dbcontextscope/blob/331dfb3266f9833fd60ec37efbce34f0e3812fd0/Mehdime.Entity/Implementations/DbContextScope.cs#L99)):*
<details><summary><i>Previously, onarres (Johnny Serrano) wrote…</i></summary><blockquote>

I like forcing people to send the token in rather than giving them a convenient way out
</blockquote></details>

You like to be special don't you?

**Comment by onarres** [comment]
___
*[Mehdime.Entity/Implementations/DbContextScope.cs, line 99 at r1](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrqlr08ESUcJVVCTHC:-LMrsHUj7O9EzBUzxxXi:bh2hkll) ([raw file](https://github.com/derhally/dbcontextscope/blob/331dfb3266f9833fd60ec37efbce34f0e3812fd0/Mehdime.Entity/Implementations/DbContextScope.cs#L99)):*
<details><summary><i>Previously, derhally (Zeid) wrote…</i></summary><blockquote>

You like to be special don't you?
</blockquote></details>

Ha ha, yup.

**Comment by onarres** [comment]
*[a discussion](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrlsz6A9HtfYaBRYij:-LMrsOIB3Cycd0m30wum:b-os8ws) (no related file):*
<details><summary><i>Previously, derhally (Zeid) wrote…</i></summary><blockquote>

Did you notice you can increase the width of the viewable area?
</blockquote></details>

So when there is a question, it still displays as "red' in the status even though I acknowledged I have read it.

---

**Comment by onarres** [comment]
___
*[DemoApplication/Program.cs, line 34 at r1](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrICP07md05EpUAlOz:-LMrsWHY0L28FBN0dgYF:b2nign6) ([raw file](https://github.com/derhally/dbcontextscope/blob/331dfb3266f9833fd60ec37efbce34f0e3812fd0/DemoApplication/Program.cs#L34)):*
<details><summary><i>Previously, derhally (Zeid) wrote…</i></summary><blockquote>

DELETE!
</blockquote></details>

yes

**Comment by derhally** [comment]
*[a discussion](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrLYe_Bv_vWyU1bOkr:-LMrt55j9uzDoh7-2RBR:b-x6jysi) (no related file):*
<details><summary><i>Previously, onarres (Johnny Serrano) wrote…</i></summary><blockquote>

This is a comment.
</blockquote></details>

Working

---

**Comment by derhally** [comment]
___
*[Mehdime.Entity/Implementations/DbContextScope.cs, line 99 at r1](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrqlr08ESUcJVVCTHC:-LMru4K1BGUpov1h96nc:b-hq72lh) ([raw file](https://github.com/derhally/dbcontextscope/blob/331dfb3266f9833fd60ec37efbce34f0e3812fd0/Mehdime.Entity/Implementations/DbContextScope.cs#L99)):*
<details><summary><i>Previously, onarres (Johnny Serrano) wrote…</i></summary><blockquote>

Ha ha, yup.
</blockquote></details>

are you happy now?

**Comment by onarres** [comment]
___
*[DemoApplication/Migrations/20180906203009_InitialCreate.cs, line 10 at r1](https://reviewable.io/reviews/derhally/dbcontextscope/1#-LMrL9U46IjX3OL2UqLr:-LMrxnNyDsILKlZOcBeW:b8fjs5x) ([raw file](https://github.com/derhally/dbcontextscope/blob/331dfb3266f9833fd60ec37efbce34f0e3812fd0/DemoApplication/Migrations/20180906203009_InitialCreate.cs#L10)):*
<details><summary><i>Previously, derhally (Zeid) wrote…</i></summary><blockquote>

I don't know if you can see all the places where you have commented.   I don't see a way to do that.
</blockquote></details>

I can click on the icon that looks like a comic message circle thing and it cycles through the conversations.

**Pull request closed without merging**
